/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP address": {                                  "en": "IP address",                                      "de": "IP Adresse",                                      "ru": "айпи адрес",                                      "pt": "endereço de IP",                                  "nl": "IP adres",                                        "fr": "adresse IP",                                      "it": "indirizzo IP",                                    "es": "dirección IP",                                    "pl": "adres IP",                                        "zh-cn": "IP地址"},
    "Login": {                                       "en": "Login",                                           "de": "Anmeldung",                                       "ru": "Авторизоваться",                                  "pt": "Conecte-se",                                      "nl": "Log in",                                          "fr": "S'identifier",                                    "it": "Accesso",                                         "es": "Iniciar sesión",                                  "pl": "Zaloguj sie",                                     "zh-cn": "登录"},
    "Network settings": {                            "en": "Network settings",                                "de": "Netzwerkeinstellungen",                           "ru": "Сетевые настройки",                               "pt": "Configurações de rede",                           "nl": "Netwerkinstellingen",                             "fr": "Paramètres réseau",                               "it": "Impostazioni di rete",                            "es": "Configuración de red",                            "pl": "Ustawienia sieci",                                "zh-cn": "网络设置"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "Update": {                                      "en": "Update",                                          "de": "Update",                                          "ru": "Обновить",                                        "pt": "Atualizar",                                       "nl": "Bijwerken",                                       "fr": "Mettre à jour",                                   "it": "Aggiornare",                                      "es": "Actualizar",                                      "pl": "Aktualizacja",                                    "zh-cn": "更新资料"},
    "Update interval": {                             "en": "Update interval",                                 "de": "Updateintervall",                                 "ru": "Интервал обновления",                             "pt": "Intervalo de atualização",                        "nl": "Bijwerkingsonderbreking",                         "fr": "Intervalle de mise à jour",                       "it": "Intervallo di aggiornamento",                     "es": "Intervalo de actualización",                      "pl": "Interwał aktualizacji",                           "zh-cn": "更新间隔"},
    "Update mode": {                                 "en": "Update mode",                                     "de": "Updatemodus",                                     "ru": "Режим обновления",                                "pt": "Modo de atualização",                             "nl": "Update-modus",                                    "fr": "Mode de mise à jour",                             "it": "Modalità di aggiornamento",                       "es": "Modo de actualizacion",                           "pl": "Tryb aktualizacji",                               "zh-cn": "更新方式"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "имя пользователя",                                "pt": "Nome do usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
};