/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Add": { "en": "Add", "de": "Hinzufügen", "ru": "Добавить", "pt": "Adicionar", "nl": "Toevoegen", "fr": "Ajouter", "it": "Inserisci", "es": "Añadir", "pl": "Dodaj", "zh-cn": "加" },
    "IP address": { "en": "IP address", "de": "IP Adresse", "ru": "айпи адрес", "pt": "endereço de IP", "nl": "IP adres", "fr": "adresse IP", "it": "indirizzo IP", "es": "dirección IP", "pl": "adres IP", "zh-cn": "IP地址" },
    "Login": { "en": "Login", "de": "Login", "ru": "Авторизоваться", "pt": "Conecte-se", "nl": "Log in", "fr": "S'identifier", "it": "Accesso", "es": "Iniciar sesión", "pl": "Zaloguj sie", "zh-cn": "登录" },
    "Network settings": { "en": "Network settings", "de": "Netzwerkeinstellungen", "ru": "Сетевые настройки", "pt": "Configurações de rede", "nl": "Netwerkinstellingen", "fr": "Paramètres réseau", "it": "Impostazioni di rete", "es": "Configuración de red", "pl": "Ustawienia sieci", "zh-cn": "网络设置" },
    "Password": { "en": "Password", "de": "Passwort", "ru": "пароль", "pt": "Senha", "nl": "Wachtwoord", "fr": "Mot de passe", "it": "Parola d'ordine", "es": "Contraseña", "pl": "Hasło", "zh-cn": "密码" },
    "Port": { "en": "Port", "de": "Port", "ru": "порт", "pt": "Porta", "nl": "Haven", "fr": "Port", "it": "Porta", "es": "Puerto", "pl": "Port", "zh-cn": "港口" },
    "Update": { "en": "Update", "de": "Update", "ru": "Обновить", "pt": "Atualizar", "nl": "Bijwerken", "fr": "Mise à jour", "it": "Aggiornare", "es": "Actualizar", "pl": "Aktualizacja", "zh-cn": "更新资料" },
    "Update clients": { "en": "Update clients", "de": "Clients aktualisieren", "ru": "Обновление клиентов", "pt": "Atualizar clientes", "nl": "Cliënten bijwerken", "fr": "Mettre à jour les clients", "it": "Aggiorna client", "es": "Actualizar clientes", "pl": "Zaktualizuj klientów", "zh-cn": "更新客户" },
    "Update devices": { "en": "Update devices", "de": "Devices aktualisieren", "ru": "Обновление устройств", "pt": "Atualizar dispositivos", "nl": "Apparaten updaten", "fr": "Mettre à jour les appareils", "it": "Aggiorna dispositivi", "es": "Actualizar dispositivos", "pl": "Zaktualizuj urządzenia", "zh-cn": "更新设备" },
    "Update health": { "en": "Update health", "de": "Health aktualisieren", "ru": "Обновление здоровья", "pt": "Atualizar integridade", "nl": "Update gezondheid", "fr": "Mettre à jour la santé", "it": "Aggiorna integrità", "es": "Actualizar salud", "pl": "Zaktualizuj zdrowie", "zh-cn": "更新健康" },
    "Update interval": { "en": "Update interval", "de": "Updateintervall", "ru": "Интервал обновления", "pt": "Intervalo de atualização", "nl": "Bijwerkingsonderbreking", "fr": "Intervalle de mise à jour", "it": "Intervallo di aggiornamento", "es": "Intervalo de actualización", "pl": "Interwał aktualizacji", "zh-cn": "更新间隔" },
    "Update networks": { "en": "Update networks", "de": "Networks aktualisieren", "ru": "Обновление сетей", "pt": "Atualizar redes", "nl": "Werk netwerken bij", "fr": "Mettre à jour les réseaux", "it": "Aggiorna reti", "es": "Actualizar redes", "pl": "Zaktualizuj sieci", "zh-cn": "更新网络" },
    "Update system information": { "en": "Update system information", "de": "Systeminformationen aktualisieren", "ru": "Обновление системной информации", "pt": "Atualizar informações do sistema", "nl": "Systeeminformatie bijwerken", "fr": "Mettre à jour les informations système", "it": "Aggiorna le informazioni di sistema", "es": "Actualizar información del sistema", "pl": "Zaktualizuj informacje o systemie", "zh-cn": "更新系统信息" },
    "Update WLANs": { "en": "Update WLANs", "de": "WLANs aktualisieren", "ru": "Обновить WLAN", "pt": "Atualizar WLANs", "nl": "WLAN's bijwerken", "fr": "Mettre à jour les WLAN", "it": "Aggiorna WLAN", "es": "Actualizar WLAN", "pl": "Zaktualizuj sieci WLAN", "zh-cn": "更新WLAN" },
    "Update vouchers": { "en": "Update vouchers", "de": "Vouchers aktualisieren", "ru": "Обновить ваучеры", "pt": "Atualizar comprovantes", "nl": "Vouchers bijwerken", "fr": "Mettre à jour les bons", "it": "Aggiorna i voucher", "es": "Actualizar comprobantes", "pl": "Zaktualizuj kupony", "zh-cn": "更新优惠券" },
    "Username": { "en": "Username", "de": "Username", "ru": "имя пользователя", "pt": "Nome do usuário", "nl": "Gebruikersnaam", "fr": "Nom d'utilisateur", "it": "Nome utente", "es": "Nombre de usuario", "pl": "Nazwa Użytkownika", "zh-cn": "用户名" },

    "Filter objects": {
        "en": "Filter objects",
        "de": "Objekte filtern",
        "ru": "Фильтровать объекты",
        "pt": "Filtrar objetos",
        "nl": "Objecten filteren",
        "fr": "Filtrer les objets",
        "it": "Filtra oggetti",
        "es": "Filtrar objetos",
        "pl": "Filtruj obiekty",
        "zh-cn": "过滤对象"
    },
    "Filter states": {
        "en": "Filter states",
        "de": "States filtern",
        "ru": "Фильтр состояний",
        "pt": "Estados do filtro",
        "nl": "Filterstatussen",
        "fr": "États du filtre",
        "it": "Stati del filtro",
        "es": "Estados de filtro",
        "pl": "Filtruj stany",
        "zh-cn": "过滤状态"
    },
    "Hint:": {
        "en": "Hint:",
        "de": "Hinweis:",
        "ru": "Подсказка:",
        "pt": "Dica:",
        "nl": "Tip:",
        "fr": "Allusion:",
        "it": "Suggerimento:",
        "es": "Insinuación:",
        "pl": "Wskazówka:",
        "zh-cn": "暗示："
    },
    "To calculate is_online, last_seen_by_uap and last_seen_by_usw need to be activated additionally.": {
        "en": "To calculate is_online, last_seen_by_uap and last_seen_by_usw need to be activated additionally.",
        "de": "Um is_online zu berechnen, müssen last_seen_by_uap und last_seen_by_usw zusätzlich aktiviert werden.",
        "ru": "Для расчета is_online необходимо дополнительно активировать last_seen_by_uap и last_seen_by_usw.",
        "pt": "Para calcular is_online, last_seen_by_uap e last_seen_by_usw precisam ser ativados adicionalmente.",
        "nl": "Om te berekenen is_online, last_seen_by_uap en last_seen_by_usw moeten bovendien worden geactiveerd.",
        "fr": "Pour calculer is_online, last_seen_by_uap et last_seen_by_usw doivent être activés en plus.",
        "it": "Per calcolare is_online, last_seen_by_uap e last_seen_by_usw devono essere attivati ulteriormente.",
        "es": "Para calcular is_online, last_seen_by_uap y last_seen_by_usw deben activarse adicionalmente.",
        "pl": "Aby obliczyć is_online, należy dodatkowo aktywować last_seen_by_uap i last_seen_by_usw.",
        "zh-cn": "要计算is_online，需要另外激活last_seen_by_uap和last_seen_by_usw。"
    },
    "Offset for is_online": {
        "en": "Offset for is_online",
        "de": "Offset für is_online",
        "ru": "Смещение для is_online",
        "pt": "Deslocamento para is_online",
        "nl": "Offset voor is_online",
        "fr": "Décalage pour is_online",
        "it": "Offset per is_online",
        "es": "Offset para is_online",
        "pl": "Przesunięcie dla is_online",
        "zh-cn": "is_online的偏移量"
    },
    "Settings for clients": {
        "en": "Settings for clients",
        "de": "Einstellungen für Clients",
        "ru": "Настройки для клиентов",
        "pt": "Configurações para clientes",
        "nl": "Instellingen voor klanten",
        "fr": "Paramètres pour les clients",
        "it": "Impostazioni per i clienti",
        "es": "Configuraciones para clientes",
        "pl": "Ustawienia dla klientów",
        "zh-cn": "客户端设置"
    },

    "Settings for voucher creation": {
        "en": "Settings for voucher creation",
        "de": "Einstellungen für die Voucher Erstellung",
        "ru": "Настройки для создания ваучеров",
        "pt": "Configurações para criação de comprovante",
        "nl": "Instellingen voor het maken van vouchers",
        "fr": "Paramètres pour la création de bons",
        "it": "Impostazioni per la creazione di voucher",
        "es": "Configuraciones para la creación de cupones",
        "pl": "Ustawienia tworzenia kuponów",
        "zh-cn": "凭证创建的设置"
    },
    "Number of vouchers": {
        "en": "Number of vouchers",
        "de": "Anzahl der Vouchers",
        "ru": "Количество ваучеров",
        "pt": "Número de vouchers",
        "nl": "Aantal vouchers",
        "fr": "Nombre de bons",
        "it": "Numero di buoni",
        "es": "Numero de cupones",
        "pl": "Liczba kuponów",
        "zh-cn": "凭证数量"
    },
    "Duration in minutes": {
        "en": "Duration in minutes",
        "de": "Dauer in Minuten",
        "ru": "Продолжительность в минутах",
        "pt": "Duração em minutos",
        "nl": "Duur in minuten",
        "fr": "Durée en minutes",
        "it": "Durata in minuti",
        "es": "Duración en minutos",
        "pl": "Czas trwania w minutach",
        "zh-cn": "持续时间（分钟）"
    },
    "Usage quota": {
        "en": "Usage quota",
        "de": "Nutzungsquote",
        "ru": "Квота использования",
        "pt": "Cota de uso",
        "nl": "Gebruiksquotum",
        "fr": "Quota d'utilisation",
        "it": "Quota di utilizzo",
        "es": "Cuota de uso",
        "pl": "Limit wykorzystania",
        "zh-cn": "使用配额"
    },
    "Upload limit in Kbps": {
        "en": "Upload limit in Kbps",
        "de": "Upload-Limit in Kbps",
        "ru": "Ограничение загрузки в кбит / с",
        "pt": "Limite de upload em Kbps",
        "nl": "Uploadlimiet in Kbps",
        "fr": "Limite de téléchargement en Kbps",
        "it": "Limite di upload in Kbps",
        "es": "Límite de carga en Kbps",
        "pl": "Limit przesyłania w Kb / s",
        "zh-cn": "上传限制（以Kbps为单位）"
    },
    "Download limit in Kbps": {
        "en": "Download limit in Kbps",
        "de": "Download-Limit in Kbps",
        "ru": "Ограничение загрузки в кбит / с",
        "pt": "Limite de download em Kbps",
        "nl": "Downloadlimiet in Kbps",
        "fr": "Limite de téléchargement en Kbps",
        "it": "Limite di download in Kbps",
        "es": "Límite de descarga en Kbps",
        "pl": "Limit pobierania w Kb / s",
        "zh-cn": "下载限制（以Kbps为单位）"
    },
    "MB quota": {
        "en": "MB quota",
        "de": "MB Kontingent",
        "ru": "Квота в мегабайтах",
        "pt": "Cota de MB",
        "nl": "MB-quota",
        "fr": "Quota de Mo",
        "it": "Quota MB",
        "es": "Cuota de MB",
        "pl": "Limit MB",
        "zh-cn": "MB配额"
    },

    // sysinfo
    "Hostname": {
        "en": "Hostname",
        "de": "Hostname",
        "ru": "Hostname",
        "pt": "nome de anfitrião",
        "nl": "Hostnaam",
        "fr": "Nom d'hôte",
        "it": "Nome host",
        "es": "Nombre de host",
        "pl": "Nazwa hosta",
        "zh-cn": "主机名"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Nom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Imię",
        "zh-cn": "名称"
    },
    "Previous version": {
        "en": "Previous version",
        "de": "Vorherige Version",
        "ru": "Предыдущая версия",
        "pt": "Versão anterior",
        "nl": "Vorige versie",
        "fr": "La version précédente",
        "it": "Versione precedente",
        "es": "Versión previa",
        "pl": "Poprzednia wersja",
        "zh-cn": "先前版本"
    },
    "Update available": {
        "en": "Update available",
        "de": "Update verfügbar",
        "ru": "Обновления доступны",
        "pt": "Atualização disponível",
        "nl": "Update beschikbaar",
        "fr": "Mise à jour disponible",
        "it": "Aggiornamento disponibile",
        "es": "Actualización disponible",
        "pl": "Dostępna aktualizacja",
        "zh-cn": "有可用更新"
    },
    "Update downloaded": {
        "en": "Update downloaded",
        "de": "Update heruntergeladen",
        "ru": "Обновление загружено",
        "pt": "Atualização baixada",
        "nl": "Update gedownload",
        "fr": "Mise à jour téléchargée",
        "it": "Aggiornamento scaricato",
        "es": "Actualización descargada",
        "pl": "Aktualizacja pobrana",
        "zh-cn": "更新下载"
    },
    "Version": {
        "en": "Version",
        "de": "Version",
        "ru": "Версия",
        "pt": "Versão",
        "nl": "Versie",
        "fr": "Version",
        "it": "Versione",
        "es": "Versión",
        "pl": "Wersja",
        "zh-cn": "版"
    },

    // clients
    "Is guest by UAP": {
        "en": "Is guest by UAP",
        "de": "Ist Gast von UAP",
        "ru": "Гость UAP",
        "pt": "É convidado pela UAP",
        "nl": "Is te gast bij UAP",
        "fr": "Est invité par UAP",
        "it": "È ospite di UAP",
        "es": "Es invitado por la UAP",
        "pl": "Jest gościem UAP",
        "zh-cn": "是UAP的客人"
    },
    "Is guest by UGW": {
        "en": "Is guest by UGW",
        "de": "Ist Gast bei UGW",
        "ru": "Гость от UGW",
        "pt": "É convidado por UGW",
        "nl": "Is te gast bij UGW",
        "fr": "Est invité par UGW",
        "it": "È ospite di UGW",
        "es": "Es invitado por UGW",
        "pl": "Jest gościem UGW",
        "zh-cn": "是UGW的客人"
    },
    "Is guest by USW": {
        "en": "Is guest by USW",
        "de": "Ist Gast von USW",
        "ru": "Гость USW",
        "pt": "É convidado pela USW",
        "nl": "Is te gast bij USW",
        "fr": "Est invité par USW",
        "it": "È ospite di USW",
        "es": "Es invitado por USW",
        "pl": "Jest gościem USW",
        "zh-cn": "是USW的客人"
    },
    "Last seen by UAP": {
        "en": "Last seen by UAP",
        "de": "Zuletzt gesehen von UAP",
        "ru": "Последнее посещение UAP",
        "pt": "Visto pela última vez pela UAP",
        "nl": "Laatst gezien door UAP",
        "fr": "Vu pour la dernière fois par UAP",
        "it": "Visto l'ultima volta da UAP",
        "es": "Visto por última vez por UAP",
        "pl": "Ostatnio widziany przez UAP",
        "zh-cn": "UAP上次查看"
    },
    "Last seen by UGW": {
        "en": "Last seen by UGW",
        "de": "Zuletzt gesehen von UGW",
        "ru": "Последний раз видели UGW",
        "pt": "Visto pela última vez por UGW",
        "nl": "Laatst gezien door UGW",
        "fr": "Vu pour la dernière fois par l'UGW",
        "it": "Visto l'ultima volta da UGW",
        "es": "Visto por última vez por UGW",
        "pl": "Ostatnio widziany przez UGW",
        "zh-cn": "UGW上次查看"
    },
    "Last seen by USW": {
        "en": "Last seen by USW",
        "de": "Zuletzt gesehen von USW",
        "ru": "Последнее посещение USW",
        "pt": "Visto pela última vez por USW",
        "nl": "Laatst gezien door USW",
        "fr": "Vu pour la dernière fois par USW",
        "it": "Visto l'ultima volta da USW",
        "es": "Visto por última vez por USW",
        "pl": "Ostatnio widziany przez USW",
        "zh-cn": "USW上次查看"
    },
    "Uptime by UAP": {
        "en": "Uptime by UAP",
        "de": "Betriebszeit von UAP",
        "ru": "Время работы от UAP",
        "pt": "Uptime por UAP",
        "nl": "Uptime door UAP",
        "fr": "Uptime by UAP",
        "it": "Uptime di UAP",
        "es": "Tiempo de actividad por UAP",
        "pl": "Czas działania przez UAP",
        "zh-cn": "UAP的正常运行时间"
    },
    "Uptime by UGW": {
        "en": "Uptime by UGW",
        "de": "Uptime von UGW",
        "ru": "Uptime от UGW",
        "pt": "Uptime por UGW",
        "nl": "Uptime van UGW",
        "fr": "Uptime by UGW",
        "it": "Uptime di UGW",
        "es": "Tiempo de actividad por UGW",
        "pl": "Uptime przez UGW",
        "zh-cn": "UGW的正常运行时间"
    },
    "Uptime by USW": {
        "en": "Uptime by USW",
        "de": "Verfügbarkeit von USW",
        "ru": "Время работы от USW",
        "pt": "Uptime por USW",
        "nl": "Uptime door USW",
        "fr": "Uptime by USW",
        "it": "Uptime di USW",
        "es": "Tiempo de actividad por USW",
        "pl": "Czas pracy przez USW",
        "zh-cn": "USW的正常运行时间"
    },
    "Access Point MAC address": {
        "en": "Access Point MAC address",
        "de": "Access Point MAC-Adresse",
        "ru": "MAC-адрес точки доступа",
        "pt": "Endereço MAC do ponto de acesso",
        "nl": "MAC-adres van toegangspunt",
        "fr": "Adresse MAC du point d'accès",
        "it": "Indirizzo MAC del punto di accesso",
        "es": "Dirección MAC del punto de acceso",
        "pl": "Adres MAC punktu dostępu",
        "zh-cn": "接入点MAC地址"
    },
    "First seen": {
        "en": "First seen",
        "de": "Zum ersten Mal gesehen",
        "ru": "Впервые увиденный",
        "pt": "Visto pela primeira vez",
        "nl": "Eerst gezien",
        "fr": "Vu la première fois",
        "it": "Visto per la prima volta",
        "es": "Visto por primera vez",
        "pl": "Pierwszy widziany",
        "zh-cn": "初见"
    },
    "Hostname": {
        "en": "Hostname",
        "de": "Hostname",
        "ru": "Hostname",
        "pt": "nome de anfitrião",
        "nl": "Hostnaam",
        "fr": "Nom d'hôte",
        "it": "Nome host",
        "es": "Nombre de host",
        "pl": "Nazwa hosta",
        "zh-cn": "主机名"
    },
    "IP address": {
        "en": "IP address",
        "de": "IP Adresse",
        "ru": "айпи адрес",
        "pt": "endereço de IP",
        "nl": "IP adres",
        "fr": "adresse IP",
        "it": "indirizzo IP",
        "es": "dirección IP",
        "pl": "adres IP",
        "zh-cn": "IP地址"
    },
    "Is guest": {
        "en": "Is guest",
        "de": "Ist Gast",
        "ru": "Гость",
        "pt": "É convidado",
        "nl": "Is gast",
        "fr": "Est invité",
        "it": "È ospite",
        "es": "Es invitado",
        "pl": "Jest gościem",
        "zh-cn": "是客人"
    },
    "Is wired": {
        "en": "Is wired",
        "de": "Ist verkabelt",
        "ru": "Проводной",
        "pt": "Está ligado",
        "nl": "Is bedraad",
        "fr": "Est câblé",
        "it": "È cablato",
        "es": "Está conectado",
        "pl": "Jest podłączony",
        "zh-cn": "有线的"
    },
    "Last seen": {
        "en": "Last seen",
        "de": "Zuletzt gesehen",
        "ru": "В последний раз видел",
        "pt": "Visto pela última vez",
        "nl": "Laatst gezien",
        "fr": "Vu pour la dernière fois",
        "it": "Ultima visualizzazione",
        "es": "Ultima vez visto",
        "pl": "Ostatnio widziany",
        "zh-cn": "最后一次露面"
    },
    "MAC address": {
        "en": "MAC address",
        "de": "MAC-Adresse",
        "ru": "MAC-адрес",
        "pt": "Endereço MAC",
        "nl": "Mac adres",
        "fr": "Adresse Mac",
        "it": "Indirizzo MAC",
        "es": "Dirección MAC",
        "pl": "Adres MAC",
        "zh-cn": "MAC地址"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Nom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Imię",
        "zh-cn": "名称"
    },
    "Network": {
        "en": "Network",
        "de": "Netzwerk",
        "ru": "сеть",
        "pt": "Rede",
        "nl": "Netwerk",
        "fr": "Réseau",
        "it": "Rete",
        "es": "Red",
        "pl": "Sieć",
        "zh-cn": "网络"
    },
    "Note": {
        "en": "Note",
        "de": "Hinweis",
        "ru": "Запись",
        "pt": "Nota",
        "nl": "Notitie",
        "fr": "Remarque",
        "it": "Nota",
        "es": "Nota",
        "pl": "Uwaga",
        "zh-cn": "注意"
    },
    "Noted": {
        "en": "Noted",
        "de": "Notiert",
        "ru": "Отметил",
        "pt": "Notado",
        "nl": "Dat is genoteerd",
        "fr": "c'est noté",
        "it": "noto",
        "es": "Célebre",
        "pl": "Odnotowany",
        "zh-cn": "已记录"
    },
    "RSSI": {
        "en": "RSSI",
        "de": "RSSI",
        "ru": "RSSI",
        "pt": "RSSI",
        "nl": "RSSI",
        "fr": "RSSI",
        "it": "RSSI",
        "es": "RSSI",
        "pl": "RSSI",
        "zh-cn": "RSSI"
    },
    "RX": {
        "en": "RX",
        "de": "RX",
        "ru": "RX",
        "pt": "RX",
        "nl": "RX",
        "fr": "RX",
        "it": "RX",
        "es": "RX",
        "pl": "RX",
        "zh-cn": "接收"
    },
    "Satisfaction": {
        "en": "Satisfaction",
        "de": "Erlebnis",
        "ru": "удовлетворение",
        "pt": "Satisfação",
        "nl": "Tevredenheid",
        "fr": "la satisfaction",
        "it": "Soddisfazione",
        "es": "Satisfacción",
        "pl": "Zadowolenie",
        "zh-cn": "满足"
    },
    "Signal": {
        "en": "Signal",
        "de": "Signal",
        "ru": "Сигнал",
        "pt": "Sinal",
        "nl": "Signaal",
        "fr": "Signal",
        "it": "Segnale",
        "es": "Señal",
        "pl": "Sygnał",
        "zh-cn": "信号"
    },
    "Switch MAC address": {
        "en": "Switch MAC address",
        "de": "MAC-Adresse wechseln",
        "ru": "Переключить MAC-адрес",
        "pt": "Alternar endereço MAC",
        "nl": "Schakel MAC-adres",
        "fr": "Changer d'adresse MAC",
        "it": "Cambia indirizzo MAC",
        "es": "Cambiar dirección MAC",
        "pl": "Zmień adres MAC",
        "zh-cn": "切换MAC地址"
    },
    "Switch port": {
        "en": "Switch port",
        "de": "Port wechseln",
        "ru": "Порт переключения",
        "pt": "Porta do switch",
        "nl": "Switch poort",
        "fr": "Port de commutateur",
        "it": "Porta di commutazione",
        "es": "Cambiar de puerto",
        "pl": "Zmień port",
        "zh-cn": "开关口"
    },
    "TX": {
        "en": "TX",
        "de": "TX",
        "ru": "Техас",
        "pt": "TX",
        "nl": "TX",
        "fr": "TX",
        "it": "TX",
        "es": "TX",
        "pl": "TX",
        "zh-cn": "得克萨斯州"
    },
    "Uptime": {
        "en": "Uptime",
        "de": "Betriebszeit",
        "ru": "Uptime",
        "pt": "Tempo de atividade",
        "nl": "Uptime",
        "fr": "Uptime",
        "it": "uptime",
        "es": "Tiempo de actividad",
        "pl": "Czas pracy",
        "zh-cn": "正常运行时间"
    },
    "Wired RX": {
        "en": "Wired RX",
        "de": "Wired RX",
        "ru": "Проводной прием",
        "pt": "RX com fio",
        "nl": "Bekabelde RX",
        "fr": "RX filaire",
        "it": "RX cablato",
        "es": "RX con cable",
        "pl": "Przewodowy RX",
        "zh-cn": "有线RX"
    },
    "Wired TX": {
        "en": "Wired TX",
        "de": "Kabelgebundenes TX",
        "ru": "Проводной TX",
        "pt": "TX com fio",
        "nl": "Bedrade TX",
        "fr": "TX câblé",
        "it": "TX cablata",
        "es": "TX con cable",
        "pl": "Przewodowy TX",
        "zh-cn": "有线TX"
    },

    // devices
    "General temperature": {
        "en": "General temperature",
        "de": "Allgemeine Temperatur",
        "ru": "Общая температура",
        "pt": "Temperatura geral",
        "nl": "Algemene temperatuur",
        "fr": "Température générale",
        "it": "Temperatura generale",
        "es": "Temperatura general",
        "pl": "Ogólna temperatura",
        "zh-cn": "一般温度"
    },
    "Number of guests": {
        "en": "Number of guests",
        "de": "Anzahl der Gäste",
        "ru": "Количество гостей",
        "pt": "Número de convidados",
        "nl": "Aantal gasten",
        "fr": "Nombre d'invités",
        "it": "Numero di invitati",
        "es": "Número de invitados",
        "pl": "Liczba gości",
        "zh-cn": "来宾人数"
    },
    "IP address": {
        "en": "IP address",
        "de": "IP Adresse",
        "ru": "айпи адрес",
        "pt": "endereço de IP",
        "nl": "IP adres",
        "fr": "adresse IP",
        "it": "indirizzo IP",
        "es": "dirección IP",
        "pl": "adres IP",
        "zh-cn": "IP地址"
    },
    "MAC address": {
        "en": "MAC address",
        "de": "MAC-Adresse",
        "ru": "MAC-адрес",
        "pt": "Endereço MAC",
        "nl": "Mac adres",
        "fr": "Adresse Mac",
        "it": "Indirizzo MAC",
        "es": "Dirección MAC",
        "pl": "Adres MAC",
        "zh-cn": "MAC地址"
    },
    "Model": {
        "en": "Model",
        "de": "Modell",
        "ru": "модель",
        "pt": "Modelo",
        "nl": "Model",
        "fr": "Modèle",
        "it": "Modello",
        "es": "Modelo",
        "pl": "Model",
        "zh-cn": "模型"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Nom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Imię",
        "zh-cn": "名称"
    },
    "Number of users": {
        "en": "Number of users",
        "de": "Anzahl der Nutzer",
        "ru": "Количество пользователей",
        "pt": "Número de usuários",
        "nl": "aantal gebruikers",
        "fr": "nombre d'utilisateurs",
        "it": "numero di utenti",
        "es": "Número de usuarios",
        "pl": "Liczba użytkowników",
        "zh-cn": "用户数"
    },
    "Enable": {
        "en": "Enable",
        "de": "Aktivieren",
        "ru": "включить",
        "pt": "Habilitar",
        "nl": "Inschakelen",
        "fr": "Activer",
        "it": "Abilitare",
        "es": "Habilitar",
        "pl": "Włączyć",
        "zh-cn": "启用"
    },
    "Is uplink": {
        "en": "Is uplink",
        "de": "Ist Uplink",
        "ru": "Это uplink",
        "pt": "É uplink",
        "nl": "Is uplink",
        "fr": "Est en liaison montante",
        "it": "È uplink",
        "es": "Es enlace ascendente",
        "pl": "Jest łączem w górę",
        "zh-cn": "是上行链路"
    },
    "ID": {
        "en": "ID",
        "de": "ICH WÜRDE",
        "ru": "Я БЫ",
        "pt": "EU IRIA",
        "nl": "ID kaart",
        "fr": "Identifiant",
        "it": "ID",
        "es": "CARNÉ DE IDENTIDAD",
        "pl": "ID",
        "zh-cn": "ID"
    },
    "POE": {
        "en": "POE",
        "de": "POE",
        "ru": "POE",
        "pt": "POE",
        "nl": "POE",
        "fr": "POE",
        "it": "POE",
        "es": "POE",
        "pl": "POE",
        "zh-cn": "POE"
    },
    "Satisfaction": {
        "en": "Satisfaction",
        "de": "Befriedigung",
        "ru": "удовлетворение",
        "pt": "Satisfação",
        "nl": "Tevredenheid",
        "fr": "la satisfaction",
        "it": "Soddisfazione",
        "es": "Satisfacción",
        "pl": "Zadowolenie",
        "zh-cn": "满足"
    },
    "Speed": {
        "en": "Speed",
        "de": "Geschwindigkeit",
        "ru": "скорость",
        "pt": "Rapidez",
        "nl": "Snelheid",
        "fr": "La vitesse",
        "it": "Velocità",
        "es": "Velocidad",
        "pl": "Prędkość",
        "zh-cn": "速度"
    },
    "Total channel utilization": {
        "en": "Total channel utilization",
        "de": "Gesamtkanalauslastung",
        "ru": "Общее использование канала",
        "pt": "Utilização total do canal",
        "nl": "Totaal kanaalgebruik",
        "fr": "Utilisation totale des canaux",
        "it": "Utilizzo totale del canale",
        "es": "Utilización total del canal",
        "pl": "Całkowite wykorzystanie kanału",
        "zh-cn": "总渠道利用率"
    },
    "RX": {
        "en": "RX",
        "de": "RX",
        "ru": "RX",
        "pt": "RX",
        "nl": "RX",
        "fr": "RX",
        "it": "RX",
        "es": "RX",
        "pl": "RX",
        "zh-cn": "接收"
    },
    "Latency": {
        "en": "Latency",
        "de": "Latenz",
        "ru": "Задержка",
        "pt": "Latência",
        "nl": "Wachttijd",
        "fr": "Latence",
        "it": "Latenza",
        "es": "Latencia",
        "pl": "Czas oczekiwania",
        "zh-cn": "潜伏"
    },
    "Run date": {
        "en": "Run date",
        "de": "Ausführungsdatum",
        "ru": "Дата прогона",
        "pt": "Data de execução",
        "nl": "Loopdatum",
        "fr": "Date d'exécution",
        "it": "Data di esecuzione",
        "es": "Fecha de ejecución",
        "pl": "Data uruchomienia",
        "zh-cn": "运行日期"
    },
    "Run time": {
        "en": "Run time",
        "de": "Laufzeit",
        "ru": "Время выполнения",
        "pt": "Tempo de execução",
        "nl": "Looptijd",
        "fr": "Durée",
        "it": "Tempo di esecuzione",
        "es": "Tiempo de ejecución",
        "pl": "Czas pracy",
        "zh-cn": "运行"
    },
    "Download": {
        "en": "Download",
        "de": "Herunterladen",
        "ru": "Скачать",
        "pt": "Baixar",
        "nl": "Downloaden",
        "fr": "Télécharger",
        "it": "Scarica",
        "es": "Descargar",
        "pl": "Pobieranie",
        "zh-cn": "下载"
    },
    "Upload": {
        "en": "Upload",
        "de": "Hochladen",
        "ru": "Загрузить",
        "pt": "Envio",
        "nl": "Uploaden",
        "fr": "Télécharger",
        "it": "Caricare",
        "es": "Subir",
        "pl": "Przekazać plik",
        "zh-cn": "上载"
    },
    "Load average 1m": {
        "en": "Load average 1m",
        "de": "Last durchschnittlich 1m",
        "ru": "Нагрузка средняя 1м",
        "pt": "Carga média 1m",
        "nl": "Laad gemiddeld 1m",
        "fr": "Charge moyenne 1m",
        "it": "Carico medio 1m",
        "es": "Carga promedio 1m",
        "pl": "Obciążenie średnio 1m",
        "zh-cn": "平均负载1m"
    },
    "Load average 5m": {
        "en": "Load average 5m",
        "de": "Last durchschnittlich 5m",
        "ru": "Нагрузка средняя 5м",
        "pt": "Carga média 5m",
        "nl": "Laad gemiddeld 5m",
        "fr": "Charge moyenne 5m",
        "it": "Carico medio 5m",
        "es": "Carga promedio 5m",
        "pl": "Obciążenie średnio 5m",
        "zh-cn": "平均负载5m"
    },
    "Load average 15m": {
        "en": "Load average 15m",
        "de": "Last durchschnittlich 15m",
        "ru": "Средняя нагрузка 15м",
        "pt": "Carga média 15m",
        "nl": "Laad gemiddeld 15m",
        "fr": "Charge moyenne 15m",
        "it": "Carico medio 15m",
        "es": "Carga promedio 15m",
        "pl": "Obciążenie średnio 15m",
        "zh-cn": "平均负载15m"
    },
    "CPU usage": {
        "en": "CPU usage",
        "de": "CPU auslastung",
        "ru": "использование процессора",
        "pt": "utilização do CPU",
        "nl": "CPU gebruik",
        "fr": "l'utilisation du processeur",
        "it": "uso della CPU",
        "es": "uso de CPU",
        "pl": "użycie procesora",
        "zh-cn": "CPU使用率"
    },
    "Memory usage": {
        "en": "Memory usage",
        "de": "Speichernutzung",
        "ru": "Использование памяти",
        "pt": "Uso de memória",
        "nl": "Geheugengebruik",
        "fr": "Utilisation de la mémoire",
        "it": "Utilizzo della memoria",
        "es": "Uso de memoria",
        "pl": "Zużycie pamięci",
        "zh-cn": "内存使用情况"
    },
    "Uptime": {
        "en": "Uptime",
        "de": "Betriebszeit",
        "ru": "Uptime",
        "pt": "Tempo de atividade",
        "nl": "Uptime",
        "fr": "Uptime",
        "it": "uptime",
        "es": "Tiempo de actividad",
        "pl": "Czas pracy",
        "zh-cn": "正常运行时间"
    },
    "Type": {
        "en": "Type",
        "de": "Art",
        "ru": "Тип",
        "pt": "Tipo",
        "nl": "Type",
        "fr": "Type",
        "it": "genere",
        "es": "Tipo",
        "pl": "Rodzaj",
        "zh-cn": "类型"
    },
    "TX": {
        "en": "TX",
        "de": "TX",
        "ru": "Техас",
        "pt": "TX",
        "nl": "TX",
        "fr": "TX",
        "it": "TX",
        "es": "TX",
        "pl": "TX",
        "zh-cn": "得克萨斯州"
    },
    "Upgradable": {
        "en": "Upgradable",
        "de": "Aufrüstbar",
        "ru": "Обновляемая",
        "pt": "Atualizável",
        "nl": "Opwaardeerbaar",
        "fr": "Évolutif",
        "it": "aggiornabile",
        "es": "Actualizable",
        "pl": "Możliwość aktualizacji",
        "zh-cn": "可升级"
    },
    "Upgrade to firmware": {
        "en": "Upgrade to firmware",
        "de": "Upgrade auf Firmware",
        "ru": "Обновление до прошивки",
        "pt": "Atualize para o firmware",
        "nl": "Upgrade naar firmware",
        "fr": "Mise à niveau vers le firmware",
        "it": "Aggiornamento al firmware",
        "es": "Actualizar a firmware",
        "pl": "Uaktualnij do oprogramowania układowego",
        "zh-cn": "升级到固件"
    },
    "Channel": {
        "en": "Channel",
        "de": "Kanal",
        "ru": "канал",
        "pt": "Canal",
        "nl": "Kanaal",
        "fr": "Canal",
        "it": "Canale",
        "es": "Canal",
        "pl": "Kanał",
        "zh-cn": "渠道"
    },

    // wlans
    "Enabled": {
        "en": "Enabled",
        "de": "aktiviert",
        "ru": "Включено",
        "pt": "ativado",
        "nl": "Ingeschakeld",
        "fr": "Activée",
        "it": "Abilitato",
        "es": "Habilitado",
        "pl": "Włączone",
        "zh-cn": "已启用"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Nom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Imię",
        "zh-cn": "名称"
    },
    "Security": {
        "en": "Security",
        "de": "Sicherheit",
        "ru": "Безопасность",
        "pt": "Segurança",
        "nl": "Veiligheid",
        "fr": "Sécurité",
        "it": "Sicurezza",
        "es": "Seguridad",
        "pl": "Bezpieczeństwo",
        "zh-cn": "安全"
    },
    "VLAN": {
        "en": "VLAN",
        "de": "VLAN",
        "ru": "VLAN",
        "pt": "VLAN",
        "nl": "VLAN",
        "fr": "VLAN",
        "it": "VLAN",
        "es": "VLAN",
        "pl": "VLAN",
        "zh-cn": "虚拟局域网"
    },
    "VLAN enabled": {
        "en": "VLAN enabled",
        "de": "VLAN aktiviert",
        "ru": "VLAN включена",
        "pt": "VLAN ativado",
        "nl": "VLAN ingeschakeld",
        "fr": "VLAN activé",
        "it": "VLAN abilitata",
        "es": "VLAN habilitada",
        "pl": "VLAN włączony",
        "zh-cn": "已启用VLAN"
    },

    //networks
    "DHCP DNS enabled": {
        "en": "DHCP DNS enabled",
        "de": "DHCP DNS aktiviert",
        "ru": "DHCP DNS включен",
        "pt": "DNS DHCP ativado",
        "nl": "DHCP DNS ingeschakeld",
        "fr": "DHCP DNS activé",
        "it": "DNS DHCP abilitato",
        "es": "DNS DHCP habilitado",
        "pl": "DHCP DNS włączony",
        "zh-cn": "启用DHCP DNS"
    },
    "DHCP enabled": {
        "en": "DHCP enabled",
        "de": "DHCP aktiviert",
        "ru": "DHCP включен",
        "pt": "DHCP ativado",
        "nl": "DHCP ingeschakeld",
        "fr": "DHCP activé",
        "it": "DHCP abilitato",
        "es": "DHCP habilitado",
        "pl": "DHCP włączony",
        "zh-cn": "启用DHCP"
    },
    "DHCP leasetime": {
        "en": "DHCP leasetime",
        "de": "DHCP-Leasetime",
        "ru": "Время аренды DHCP",
        "pt": "Tempo de concessão de DHCP",
        "nl": "DHCP Lease Time",
        "fr": "Durée de vie DHCP",
        "it": "Leasetime DHCP",
        "es": "DHCP leasetime",
        "pl": "Czas dzierżawy DHCP",
        "zh-cn": "DHCP租约时间"
    },
    "DHCP start": {
        "en": "DHCP start",
        "de": "DHCP-Start",
        "ru": "Запуск DHCP",
        "pt": "Início do DHCP",
        "nl": "DHCP starten",
        "fr": "Démarrage DHCP",
        "it": "Avvio DHCP",
        "es": "Inicio DHCP",
        "pl": "Uruchomienie DHCP",
        "zh-cn": "DHCP启动"
    },
    "DHCP stop": {
        "en": "DHCP stop",
        "de": "DHCP-Stopp",
        "ru": "Остановка DHCP",
        "pt": "Parada de DHCP",
        "nl": "DHCP stop",
        "fr": "Arrêt DHCP",
        "it": "DHCP stop",
        "es": "Parada DHCP",
        "pl": "Zatrzymanie DHCP",
        "zh-cn": "DHCP停止"
    },
    "Enabled": {
        "en": "Enabled",
        "de": "aktiviert",
        "ru": "Включено",
        "pt": "ativado",
        "nl": "Ingeschakeld",
        "fr": "Activée",
        "it": "Abilitato",
        "es": "Habilitado",
        "pl": "Włączone",
        "zh-cn": "已启用"
    },
    "IP subnet": {
        "en": "IP subnet",
        "de": "IP-Subnetz",
        "ru": "IP-подсеть",
        "pt": "Sub-rede IP",
        "nl": "IP-subnet",
        "fr": "Sous-réseau IP",
        "it": "Sottorete IP",
        "es": "Subred IP",
        "pl": "Podsieć IP",
        "zh-cn": "IP子网"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Nom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Imię",
        "zh-cn": "名称"
    },
    "Network group": {
        "en": "Network group",
        "de": "Netzwerkgruppe",
        "ru": "Сетевая группа",
        "pt": "Grupo de rede",
        "nl": "Netwerkgroep",
        "fr": "Groupe de réseau",
        "it": "Gruppo di rete",
        "es": "Grupo de red",
        "pl": "Grupa sieci",
        "zh-cn": "网络组"
    },
    "Purpose": {
        "en": "Purpose",
        "de": "Zweck",
        "ru": "Цель",
        "pt": "Objetivo",
        "nl": "Doel",
        "fr": "Objectif",
        "it": "Scopo",
        "es": "Propósito",
        "pl": "Cel, powód",
        "zh-cn": "目的"
    },
    "VLAN": {
        "en": "VLAN",
        "de": "VLAN",
        "ru": "VLAN",
        "pt": "VLAN",
        "nl": "VLAN",
        "fr": "VLAN",
        "it": "VLAN",
        "es": "VLAN",
        "pl": "VLAN",
        "zh-cn": "虚拟局域网"
    },
    "VLAN enabled": {
        "en": "VLAN enabled",
        "de": "VLAN aktiviert",
        "ru": "VLAN включена",
        "pt": "VLAN ativado",
        "nl": "VLAN ingeschakeld",
        "fr": "VLAN activé",
        "it": "VLAN abilitata",
        "es": "VLAN habilitada",
        "pl": "VLAN włączony",
        "zh-cn": "已启用VLAN"
    },
    "VPN type": {
        "en": "VPN type",
        "de": "VPN-Typ",
        "ru": "Тип VPN",
        "pt": "Tipo de VPN",
        "nl": "VPN-type",
        "fr": "Type de VPN",
        "it": "Tipo di VPN",
        "es": "Tipo de VPN",
        "pl": "Typ VPN",
        "zh-cn": "VPN类型"
    },
    "WAN IP": {
        "en": "WAN IP",
        "de": "WAN IP",
        "ru": "WAN IP",
        "pt": "IP da WAN",
        "nl": "WAN IP",
        "fr": "IP WAN",
        "it": "IP WAN",
        "es": "IP WAN",
        "pl": "WAN IP",
        "zh-cn": "广域网IP"
    },

    // health
    "LAN IP": {
        "en": "LAN IP",
        "de": "LAN IP",
        "ru": "LAN IP",
        "pt": "IP da LAN",
        "nl": "LAN IP",
        "fr": "IP LAN",
        "it": "IP LAN",
        "es": "LAN IP",
        "pl": "LAN IP",
        "zh-cn": "局域网IP"
    },
    "Latency": {
        "en": "Latency",
        "de": "Latenz",
        "ru": "Задержка",
        "pt": "Latência",
        "nl": "Wachttijd",
        "fr": "Latence",
        "it": "Latenza",
        "es": "Latencia",
        "pl": "Czas oczekiwania",
        "zh-cn": "潜伏"
    },
    "Number of guests": {
        "en": "Number of guests",
        "de": "Anzahl der Gäste",
        "ru": "Количество гостей",
        "pt": "Número de convidados",
        "nl": "Aantal gasten",
        "fr": "Nombre d'invités",
        "it": "Numero di invitati",
        "es": "Número de invitados",
        "pl": "Liczba gości",
        "zh-cn": "来宾人数"
    },
    "Number of IOT": {
        "en": "Number of IOT",
        "de": "Anzahl der IOT",
        "ru": "Количество IOT",
        "pt": "Número de IOT",
        "nl": "Aantal IOT",
        "fr": "Nombre d'IOT",
        "it": "Numero di IOT",
        "es": "Número de IOT",
        "pl": "Liczba IOT",
        "zh-cn": "物联网数量"
    },
    "Number of users": {
        "en": "Number of users",
        "de": "Anzahl der Nutzer",
        "ru": "Количество пользователей",
        "pt": "Número de usuários",
        "nl": "aantal gebruikers",
        "fr": "nombre d'utilisateurs",
        "it": "numero di utenti",
        "es": "Número de usuarios",
        "pl": "Liczba użytkowników",
        "zh-cn": "用户数"
    },
    "Status": {
        "en": "Status",
        "de": "Status",
        "ru": "Положение дел",
        "pt": "Status",
        "nl": "Toestand",
        "fr": "Statut",
        "it": "Stato",
        "es": "Estado",
        "pl": "Status",
        "zh-cn": "状态"
    },
    "Subsystem": {
        "en": "Subsystem",
        "de": "Teilsystem",
        "ru": "подсистема",
        "pt": "Subsistema",
        "nl": "Subsysteem",
        "fr": "Sous-système",
        "it": "Subsystem",
        "es": "Subsistema",
        "pl": "Podsystem",
        "zh-cn": "子系统"
    },
    "Speedtest lastrun": {
        "en": "Speedtest lastrun",
        "de": "Speedtest Lastrun",
        "ru": "Speedtest lastrun",
        "pt": "Speedtest lastrun",
        "nl": "Speedtest lastrun",
        "fr": "Speedtest lastrun",
        "it": "Speedtest lastrun",
        "es": "Speedtest lastrun",
        "pl": "Speedtest Lastrun",
        "zh-cn": "Speedtest lastrun"
    },
    "Speedtest ping": {
        "en": "Speedtest ping",
        "de": "Speedtest Ping",
        "ru": "Speedtest пинг",
        "pt": "Ping Speedtest",
        "nl": "Speedtest ping",
        "fr": "Speedtest ping",
        "it": "Ping Speedtest",
        "es": "Speedtest ping",
        "pl": "Ping Speedtest",
        "zh-cn": "速度测试ping"
    },
    "Speedtest status": {
        "en": "Speedtest status",
        "de": "Speedtest-Status",
        "ru": "Статус Speedtest",
        "pt": "Status do Speedtest",
        "nl": "Speedtest-status",
        "fr": "Statut Speedtest",
        "it": "Stato Speedtest",
        "es": "Estado de prueba de velocidad",
        "pl": "Status testu prędkości",
        "zh-cn": "速度测试状态"
    },
    "Uptime": {
        "en": "Uptime",
        "de": "Betriebszeit",
        "ru": "Uptime",
        "pt": "Tempo de atividade",
        "nl": "Uptime",
        "fr": "Uptime",
        "it": "uptime",
        "es": "Tiempo de actividad",
        "pl": "Czas pracy",
        "zh-cn": "正常运行时间"
    },
    "WAN IP": {
        "en": "WAN IP",
        "de": "WAN IP",
        "ru": "WAN IP",
        "pt": "IP da WAN",
        "nl": "WAN IP",
        "fr": "IP WAN",
        "it": "IP WAN",
        "es": "IP WAN",
        "pl": "WAN IP",
        "zh-cn": "广域网IP"
    },

    // vouchers
    "Code": {
        "en": "Code",
        "de": "Code",
        "ru": "Код",
        "pt": "Código",
        "nl": "Code",
        "fr": "Code",
        "it": "Codice",
        "es": "Código",
        "pl": "Kod",
        "zh-cn": "码"
    },
    "Create time": {
        "en": "Create time",
        "de": "Zeit schaffen",
        "ru": "Создать время",
        "pt": "Criar hora",
        "nl": "Maak tijd",
        "fr": "Créer du temps",
        "it": "Crea tempo",
        "es": "Crear tiempo",
        "pl": "Stwórz czas",
        "zh-cn": "建立时间"
    },
    "Duration": {
        "en": "Duration",
        "de": "Dauer",
        "ru": "продолжительность",
        "pt": "Duração",
        "nl": "Looptijd",
        "fr": "Durée",
        "it": "Durata",
        "es": "Duración",
        "pl": "Trwanie",
        "zh-cn": "持续时间"
    },
    "Note": {
        "en": "Note",
        "de": "Hinweis",
        "ru": "Запись",
        "pt": "Nota",
        "nl": "Notitie",
        "fr": "Remarque",
        "it": "Nota",
        "es": "Nota",
        "pl": "Uwaga",
        "zh-cn": "注意"
    },
    "QOS overwrite": {
        "en": "QOS overwrite",
        "de": "QOS überschreiben",
        "ru": "QOS перезаписать",
        "pt": "Substituição de QOS",
        "nl": "QOS overschrijven",
        "fr": "Écraser la qualité de service",
        "it": "Sovrascrivi QOS",
        "es": "QOS sobrescribe",
        "pl": "Zastąpienie QOS",
        "zh-cn": "QOS覆盖"
    },
    "QOS max download": {
        "en": "QOS max download",
        "de": "QOS max herunterladen",
        "ru": "QOS max скачать",
        "pt": "Download máximo do QOS",
        "nl": "QOS max download",
        "fr": "Téléchargement QOS max",
        "it": "Download massimo QOS",
        "es": "Descarga máxima de QOS",
        "pl": "Pobieranie QOS max",
        "zh-cn": "QOS max下载"
    },
    "QOS max upload": {
        "en": "QOS max upload",
        "de": "QOS max Upload",
        "ru": "Максимальная загрузка QOS",
        "pt": "Upload máximo de QOS",
        "nl": "QOS max upload",
        "fr": "Téléchargement QOS max",
        "it": "Caricamento massimo QOS",
        "es": "QOS carga máxima",
        "pl": "Przesyłanie QOS max",
        "zh-cn": "QOS max上传"
    },
    "QOS usage quota": {
        "en": "QOS usage quota",
        "de": "QOS-Nutzungskontingent",
        "ru": "Квота использования QOS",
        "pt": "Cota de uso de QOS",
        "nl": "QOS-gebruiksquotum",
        "fr": "Quota d'utilisation QOS",
        "it": "Quota di utilizzo QOS",
        "es": "Cuota de uso de QOS",
        "pl": "Limit wykorzystania QOS",
        "zh-cn": "QOS使用配额"
    },
    "Quota": {
        "en": "Quota",
        "de": "Quote",
        "ru": "квота",
        "pt": "Contingente",
        "nl": "Quota",
        "fr": "Quota",
        "it": "quota",
        "es": "Cuota",
        "pl": "Kontyngent",
        "zh-cn": "配额"
    },
    "Category Id": {
        "en": "Category Id",
        "de": "Kategorie ID",
        "ru": "Идентификатор категории",
        "pt": "Categoria ID",
        "nl": "Categorie ID",
        "fr": "Identifiant de catégorie",
        "it": "ID categoria",
        "es": "Categoria ID",
        "pl": "Identyfikator kategorii",
        "zh-cn": "类别编号"
    },
    "Application Id": {
        "en": "Application Id",
        "de": "App-ID",
        "ru": "Идентификатор приложения",
        "pt": "ID do aplicativo",
        "nl": "Applicatie ID",
        "fr": "ID d'application",
        "it": "ID applicazione",
        "es": "ID de aplicación",
        "pl": "Identyfikator aplikacji",
        "zh-cn": "申请编号"
    },
    "Known clients": {
        "en": "Known clients",
        "de": "Bekannte Endgeräte",
        "ru": "Известные клиенты",
        "pt": "Clientes conhecidos",
        "nl": "Bekende klanten",
        "fr": "Clients connus",
        "it": "Clienti noti",
        "es": "Clientes conocidos",
        "pl": "Znani klienci",
        "zh-cn": "已知客户"
    },
    "Name of Category": {
        "en": "Name of Category",
        "de": "Name der Kategorie",
        "ru": "Название категории",
        "pt": "Nome da categoria",
        "nl": "Naam van categorie",
        "fr": "Nom de la catégorie",
        "it": "Nome della categoria",
        "es": "Nombre de categoria",
        "pl": "Nazwa kategorii",
        "zh-cn": "类别名称"
    },
    "List of Application Ids": {
        "en": "List of Application Ids",
        "de": "Liste der App-IDs",
        "ru": "Список идентификаторов приложений",
        "pt": "Lista de IDs de aplicativos",
        "nl": "Lijst met toepassings-id's",
        "fr": "Liste des ID d'application",
        "it": "Elenco di ID applicazione",
        "es": "Lista de identificadores de aplicación",
        "pl": "Lista identyfikatorów aplikacji",
        "zh-cn": "申请编号清单"
    },
    "Last updated": {
        "en": "Last updated",
        "de": "Letzte Aktualisierung",
        "ru": "Последнее обновление",
        "pt": "Ultima atualização",
        "nl": "Laatst bijgewerkt",
        "fr": "Dernière mise à jour",
        "it": "Ultimo aggiornamento",
        "es": "Última actualización",
        "pl": "Ostatnio zaktualizowany",
        "zh-cn": "最近更新时间"
    },
    "type of temperature": {
        "en": "type of temperature",
        "de": "Art der Temperatur",
        "ru": "тип температуры",
        "pt": "tipo de temperatura",
        "nl": "type temperatuur",
        "fr": "type de température",
        "it": "tipo di temperatura",
        "es": "tipo de temperatura",
        "pl": "rodzaj temperatury",
        "zh-cn": "温度类型"
    },
    "temperature value": {
        "en": "temperature value",
        "de": "Temperaturwert",
        "ru": "значение температуры",
        "pt": "valor da temperatura",
        "nl": "temperatuurwaarde",
        "fr": "valeur de température",
        "it": "valore di temperatura",
        "es": "valor de temperatura",
        "pl": "wartość temperatury",
        "zh-cn": "温度值"
    },
    "size of storage": {
        "en": "size of storage",
        "de": "Größe des Speichers",
        "ru": "размер хранилища",
        "pt": "tamanho de armazenamento",
        "nl": "grootte van opslag",
        "fr": "taille de stockage",
        "it": "dimensione della memoria",
        "es": "tamaño de almacenamiento",
        "pl": "wielkość magazynu",
        "zh-cn": "储存空间"
    },
    "type of storage": {
        "en": "type of storage",
        "de": "Art des Speichers",
        "ru": "тип хранения",
        "pt": "tipo de armazenamento",
        "nl": "type opslag",
        "fr": "type de stockage",
        "it": "tipo di archiviazione",
        "es": "tipo de almacenamiento",
        "pl": "rodzaj przechowywania",
        "zh-cn": "储存类型"
    },
    "using of storage size": {
        "en": "using of storage size",
        "de": "verwendeter Speicherplatz",
        "ru": "использование размера хранилища",
        "pt": "uso do tamanho de armazenamento",
        "nl": "gebruik van opslaggrootte",
        "fr": "utilisation de la taille de stockage",
        "it": "utilizzo delle dimensioni di archiviazione",
        "es": "uso del tamaño de almacenamiento",
        "pl": "wykorzystanie wielkości pamięci",
        "zh-cn": "使用存储空间"
    },
    "memory buffer": {
        "en": "memory buffer",
        "de": "Speicherpuffer",
        "ru": "буфер памяти",
        "pt": "buffer de memória",
        "nl": "geheugenbuffer",
        "fr": "mémoire tampon",
        "it": "buffer di memoria",
        "es": "memoria intermedia",
        "pl": "bufor pamięci",
        "zh-cn": "内存缓冲区"
    },
    "memory total": {
        "en": "memory total",
        "de": "Speicher insgesamt",
        "ru": "общий объем памяти",
        "pt": "total de memória",
        "nl": "geheugen totaal",
        "fr": "mémoire totale",
        "it": "memoria totale",
        "es": "total de memoria",
        "pl": "pamięć ogółem",
        "zh-cn": "总内存"
    },
    "memory used": {
        "en": "memory used",
        "de": "Speicher verwendet",
        "ru": "используемая память",
        "pt": "memória usada",
        "nl": "geheugen gebruikt",
        "fr": "mémoire utilisée",
        "it": "memoria utilizzata",
        "es": "memoria usada",
        "pl": "używana pamięć",
        "zh-cn": "使用的内存"
    },
    "Number of clients": {
        "en": "Number of clients",
        "de": "Anzahl der Endgeräte",
        "ru": "Количество клиентов",
        "pt": "Número de clientes",
        "nl": "Aantal klanten",
        "fr": "Nombre de clients",
        "it": "Numero di clienti",
        "es": "Numero de clientes",
        "pl": "Liczba klientów",
        "zh-cn": "客户数量"
    },
    "ESSID": {
        "en": "WLAN SSID",
        "de": "WLAN SSID",
        "ru": "WLAN SSID",
        "pt": "SSID WLAN",
        "nl": "WLAN SSID",
        "fr": "SSID WLAN",
        "it": "SSID WLAN",
        "es": "SSID WLAN",
        "pl": "SSID sieci WLAN",
        "zh-cn": "WLAN SSID"
    },
    "Update DPI": {
        "en": "Update DPI (USG needed)",
        "de": "DPI aktualisieren (USG erforderlich)",
        "ru": "Обновить DPI (требуется USG)",
        "pt": "Atualização de DPI (USG necessário)",
        "nl": "DPI bijwerken (USG nodig)",
        "fr": "Mettre à jour DPI (USG nécessaire)",
        "it": "Aggiornamento DPI (USG necessario)",
        "es": "Actualizar DPI (se necesita USG)",
        "pl": "Zaktualizuj DPI (wymagane USG)",
        "zh-cn": "更新DPI（需要USG）"
    },
    "Update Gateway Traffic": {
        "en": "Update Gateway Traffic (USG needed)",
        "de": "Gateway Verkehr aktualisieren (USG erforderlich)",
        "ru": "Обновление трафика шлюза (требуется USG)",
        "pt": "Atualizar tráfego de gateway (USG necessário)",
        "nl": "Gatewayverkeer bijwerken (USG nodig)",
        "fr": "Mettre à jour le trafic de la passerelle (USG nécessaire)",
        "it": "Aggiorna traffico gateway (USG necessario)",
        "es": "Actualizar el tráfico de la puerta de enlace (se necesita USG)",
        "pl": "Zaktualizuj ruch bramy (wymagane USG)",
        "zh-cn": "更新网关流量（需要USG）"
    },
    "Date of day": {
        "en": "Date of day",
        "de": "Datum des Tages",
        "ru": "Дата дня",
        "pt": "Data do dia",
        "nl": "Datum van de dag",
        "fr": "Date du jour",
        "it": "Data del giorno",
        "es": "Fecha del dia",
        "pl": "Data dnia",
        "zh-cn": "星期几"
    },
    "Bytes sent": {
        "en": "sent",
        "de": "gesendet",
        "ru": "послал",
        "pt": "enviei",
        "nl": "verzonden",
        "fr": "envoyé",
        "it": "inviato",
        "es": "expedido",
        "pl": "wysłane",
        "zh-cn": "已发送"
    },
    "Bytes received": {
        "en": "received",
        "de": "empfangen",
        "ru": "получил",
        "pt": "recebido",
        "nl": "ontvangen",
        "fr": "reçu",
        "it": "ricevuto",
        "es": "recibido",
        "pl": "Odebrane",
        "zh-cn": "已收到"
    }
};